# Generated by Django 3.0.7 on 2020-06-08 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidat', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidat',
            old_name='addresse',
            new_name='adresse',
        ),
    ]
