# Generated by Django 3.0.7 on 2020-06-10 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('candidat', '0002_auto_20200608_1826'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accreditation', models.CharField(max_length=100)),
                ('titre_cert', models.CharField(max_length=50)),
                ('date_cert', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Ecole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_ecole', models.CharField(max_length=50)),
                ('classement', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Experience_Pro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee_debut', models.IntegerField()),
                ('annee_fin', models.IntegerField()),
                ('description_exp_pro', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('langue', models.CharField(max_length=20)),
                ('level', models.CharField(choices=[('A1', 'découverte'), ('A2', 'usuel'), ('B1', 'niveau seuil'), ('B2', 'niveau avancé'), ('C1', 'autonome'), ('C2', 'maîtrise')], default='A1', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Projet_realise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee_projet', models.IntegerField()),
                ('description_projet', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='candidat',
            name='sex',
            field=models.CharField(choices=[('H', 'Homme'), ('F', 'Femme')], default='H', max_length=1),
        ),
        migrations.CreateModel(
            name='Academic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee_debut', models.IntegerField()),
                ('annee_fin', models.IntegerField()),
                ('type_diplome', models.CharField(max_length=10)),
                ('description_academic', models.TextField(blank=True, null=True)),
                ('ecole', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='candidat.Ecole')),
            ],
        ),
        migrations.AddField(
            model_name='candidat',
            name='academic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='candidat.Academic'),
        ),
        migrations.AddField(
            model_name='candidat',
            name='certificat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='candidat.Certificat'),
        ),
        migrations.AddField(
            model_name='candidat',
            name='experience_Pro',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='candidat.Experience_Pro'),
        ),
        migrations.AddField(
            model_name='candidat',
            name='language',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='candidat.Language'),
        ),
        migrations.AddField(
            model_name='candidat',
            name='projet_realise',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='candidat.Projet_realise'),
        ),
    ]
