# Generated by Django 3.0.7 on 2020-06-07 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Academic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee_debut', models.IntegerField()),
                ('annee_fin', models.IntegerField()),
                ('type_diplome', models.CharField(max_length=10)),
                ('description_academic', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Certificat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accreditation', models.CharField(max_length=100)),
                ('titre_cert', models.CharField(max_length=50)),
                ('date_cert', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Ecole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_ecole', models.CharField(max_length=50)),
                ('classement', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Experience_Pro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee_debut', models.IntegerField()),
                ('annee_fin', models.IntegerField()),
                ('description_exp_pro', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('langue', models.CharField(max_length=20)),
                ('level', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Projet_realise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee_prjet', models.IntegerField()),
                ('description_projet', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cv.Academic')),
                ('candidat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidat.Candidat')),
                ('certificat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cv.Certificat')),
                ('experience_Pro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cv.Experience_Pro')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cv.Language')),
                ('projet_realise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cv.Projet_realise')),
            ],
        ),
        migrations.AddField(
            model_name='academic',
            name='ecole',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Cv.Ecole'),
        ),
    ]
