# Generated by Django 3.0.7 on 2020-06-08 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('candidat', '0001_initial'),
        ('Cv', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='candidat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidat.Candidat', unique=True),
        ),
    ]
