# Generated by Django 3.0.7 on 2020-06-10 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('candidat', '0002_auto_20200608_1826'),
        ('Cv', '0002_auto_20200608_1526'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projet_realise',
            old_name='annee_prjet',
            new_name='annee_projet',
        ),
        migrations.AlterField(
            model_name='cv',
            name='candidat',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='candidat.Candidat'),
        ),
        migrations.AlterField(
            model_name='language',
            name='level',
            field=models.IntegerField(),
        ),
    ]
