# Generated by Django 3.0.7 on 2020-06-10 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cv', '0003_auto_20200610_1617'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cv',
            name='academic',
        ),
        migrations.RemoveField(
            model_name='cv',
            name='candidat',
        ),
        migrations.RemoveField(
            model_name='cv',
            name='certificat',
        ),
        migrations.RemoveField(
            model_name='cv',
            name='experience_Pro',
        ),
        migrations.RemoveField(
            model_name='cv',
            name='language',
        ),
        migrations.RemoveField(
            model_name='cv',
            name='projet_realise',
        ),
        migrations.DeleteModel(
            name='Academic',
        ),
        migrations.DeleteModel(
            name='Certificat',
        ),
        migrations.DeleteModel(
            name='Cv',
        ),
        migrations.DeleteModel(
            name='Ecole',
        ),
        migrations.DeleteModel(
            name='Experience_Pro',
        ),
        migrations.DeleteModel(
            name='Language',
        ),
        migrations.DeleteModel(
            name='Projet_realise',
        ),
    ]
